--DROP TABLE users IF EXISTS;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name VARCHAR(50),
  email  VARCHAR(100),
  password VARCHAR(20),
  country VARCHAR(60),
  zipcode VARCHAR(5), 
  city VARCHAR(100), 
  street VARCHAR(200),
  day VARCHAR(2), 
  month VARCHAR(20), 
  year VARCHAR(4),  
  appid VARCHAR(200) 
);